contracts/tokens.js

Determination of _id's to cancel:
Used
```
fetch("https://api.hive-engine.com/rpc/contracts", {
"headers": {
"accept": "application/json, text/plain, */*",
"accept-language": "en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7",
"access-control-allow-origin": "*",
"content-type": "application/json",
"sec-fetch-dest": "empty",
"sec-fetch-mode": "cors",
"sec-fetch-site": "same-site"
},
"referrer": "https://hive-engine.com/",
"referrerPolicy": "strict-origin-when-cross-origin",
"body": "{\"jsonrpc\":\"2.0\",\"id\":13,\"method\":\"find\",\"params\":{\"contract\":\"tokens\",\"table\":\"pendingUnstakes\",\"query\":{\"numberTransactionsLeft\":{\"$gt\": 1}},\"limit\":1000,\"offset\":0,\"indexes\": [{\"index\": \"_id\", \"descending\": true}]}}",
"method": "POST",
"mode": "cors",
"credentials": "omit"
});
``` …

backfill to remove problematic unstakes

---

contracts/mining.js
contracts/nft.js
test/mining.js

Implements nft into mining.
Uses nft "type" property distinguish different NFTs. Mining config specifies power settings on a per type basis.
Up to four mining properties can be specified. Each of these can configure whether it is accumulated with + or * as the op.
After combining all properties of all owned NFTs, the full power is calculated by * all of the property totals.
NFTs do not have staking, so instead we use delegation to determine whether an NFT is active for mining. Delegating to the mining contract constitutes applying the nft to yourself, and delegating to others constitutes applying the nft to others.
Note that properties can be negative as well. If the op results in negative total power or NaN, note that it will result in 0 power for the account.

Hive mining nft

---

contracts/nftmarket.js
test/nftmarket.js

``if fee`` evaluates to false when its a integer of 0.
I believe typeof should be sufficient to determine whether its a `number` or `undefined`, which I think was the original intent.

Fix cannot make NFT sell order with fee of 0

---

contracts/mining.js
test/mining.js

Fix test.
Note that there was an issue with an existing test where we issued a delegate op for something that was undelegating, and that did not throw an error (may be something to fix validation for, but it doesn't hurt anything for the time being).

do not add undelegating nft balances on pool power update computation

---

contracts/tokens.js
test/mining.js

There are two issues:  The first is that on the last token release (no stake change), it does an additional stake deduction on the incorrect amount. The second is that there is a mismatch between when stake is deducted and mining power is deducted. This change consolidates the stake changes in a single place to prevent the confusion and correct the issue.

Fix over-subtraction of mining power during unstake

---

contracts/witnesses.js
plugins/P2P.js
test/witnesses.js

Missed rounds were happening because some round computations were done before the block was ready. Added a delay / retry mechanism to accomodate that.
Fix witness reward amount to match inflation.

Fix witness round hash, change reward amount to match inflation contract

---

config.json
plugins/Streamer.js

Among all listed nodes, it will send 3 QPS (configurable) at a time to each node to fetch blocks, and allows for utilizing faster nodes more efficiently (as they free up their requests more quickly). But broken nodes will slow down the whole process, so this will need some monitoring (todo-- automatically kick out repeatedly failing nodes)

Add block lookahead behavior to fetch blocks far in advance to speed up replay

---

contracts/witnesses.js

fix random selection of witnesses, it is off by lowest precision amount. See https://stackoverflow.com/questions/1527803/generating-random-whole-numbers-in-javascript-in-a-specific-range for formula
This is a difference between the two following formulas:
floor( rnd * ( TOTAL - ACC )) + ACC + eps
vs
floor( rnd * (TOTAL  - ACC - eps) + ACC + eps )
where (eps  = smallest positive token amount, ACC is top witnesses approval weight sum,  TOTAL is total witnesses approval weight sum)
Also changes rounding modes to use floor instead of round as per https://mikemcl.github.io/bignumber.js/#toFix
We should probably audit other usages of random and fix accordingly. It's a very minimal impact in general though.

small random weight selection fix to witness contract, witness contract cleanup

---

contracts/testing/tokens_unused_params.js
contracts/tokens.js
test/tokens.js

This PR makes the following changes to the tokens contract:
* move the account blacklist to params rather than keeping it hard-coded in the contract
* add list of Hive Engine owned accounts to params
* add a new validation to the create action to prevent accounts other than Hive Engine accounts from being able to create a token with SWAP in the symbol
* eliminate token creation fees for Hive Engine accounts
* clean up unused params settings & code left over from earlier fixes

Tokens safety checks

---

contracts/marketpools.js
contracts/mining.js
test/marketpools.js

- Add support for externally managed miningPower in the mining contract
- Allow token issuer to create a custom reward pool for a diesel pool, which uses liquidity provider shares as miningPower
These changes to the mining contract allow diesel pools, and other contracts in the future to re-use the lottery token issuance implementation and manage their own pool and rank of participants.

Diesel Pools lottery reward method

---

test/marketpools.js

The randomized test case was sometimes overdrawing the available balance and returning a false negative result. The amounts are scaled back and should perform reliably going forward. I found this test useful during development, but perhaps it doesn't need to be run in the production test suite at all.

marketpools randomized test case bounds fix

---

plugins/Blockchain.js
plugins/Streamer.js

Now it will take into account the additionalHashChangeBlocks, which is the scenario where for some reason or other the node is processing a hive block that changes the DB *without* producing any logs / additional block (e.g. with the automated actions). This can happen right now because of comment actions that get sent to the Blockchain plugin but get ignored due contract not being implemented and then subsequently getting filtered out.
Note that this is actually not so much of a risk because most such actions modifying the DB are idempotent (they will only happen once based on a timestamp condition, so re-running the same action again will not produce additional differences). However, this may not always be the case, so we should be proactive about preventing a state where a node restart …

fix start block detection and skip block detection

---

contracts/tokens.js
test/mining.js
test/tokens.js

Symbols with dot ("."), ETH, and BSC in them are now restricted for creation only by Hive Engine owned accounts.  This is in preparation for starting to use ETH.xxxx names for pegged ERC20 tokens and BSC.xxxx names for pegged BEP20 tokens.

Make certain symbol naming patterns reserved

---

contracts/nftauction.js
libs/Block.js
package.json
test/nftauction.js

Allows users to auction NFTs for any Price symbol.
- Fee: 1 BEE
- Max Allowed NFTs at one auction: 50
An Auction can run up to 30 days, and attempts to settle after 24 hours of lead bid. To take the lead a bid must be 5% or more from the previous bid and it resets the 24 hour timer. Bids can be cancelled anytime except 5 minutes before settlement. At any given time owner can cancel the auction or settle it with specific or the current lead bid. Bids can be updated with larger quantity at any time. owner may set a minimum bid and a final price which settles the auction immediately if hit. After settlement, the winner gets NFTs and seller gets his bid. All other bids are returned.

NFT Auction Smart Contract

---

contracts/comments.js
test/comments.js

Cleans up post and vote data after payout, as it is no longer needed.
Emit event for declined post payout so indexers can pick up the change as well.

Clean up post vote data after payout

---

plugins/Streamer.js

Allows 1.4.0 to replay from snapshots prior to the inadvertent fork.

gate new streamer behavior on forking block

---

contracts/testing/dummyTicks.js
libs/Block.js
libs/Constants.js
libs/Database.js
libs/SmartContracts.js
package.json
test/ticks.js

Register all ticking contracts into "contracts_config" table. Allows for putting more global contract settings in the future. Add "registerTick" method for registering additional ticking actions.

Add tick registration mechanism

---

contracts/mining.js
contracts/nft.js
test/mining.js
test/nft.js

Allow specifying equip field or mining power field to allow NFT creator to control what is considered as equipped and allow for extra mining power to be added per nft instance.
These can configured independently, and cannot be changed once a reward pool is created.
We add a new contract call from nft contract to mining contract whenever setProperties is called, which allows for the corresponding mining power to be updated.

NFT mining equip fields and extra mining power fields

---

contracts/tokenfunds.js
test/tokenfunds.js

- The call from tokens contract was adding and updating unnecessary tokens to the accounts table. It will now only store and update voteTokens used by the account in various DTFs.
- Proposal weight now checks the token against the voteToken and updates only when needed.
- CreateSSC update to recalculate all weights and remove unnecessary tokens from accounts

fix updateProposalApprovals weight calculation

---

contracts/marketpools.js
test/marketpools.js

- Slippage protection for `swapTokens` using optional parameters `minAmountOut` / `maxAmountIn` depending on trade direction. Transactions without these parameters or those that specify `maxSlippage` can still be executed. `maxSlippage` in the swapTokens action no longer has any effect.
- Price impact control is retained for adding liquidity. It is no longer applied to `swapTokens`.

pools - separate slippage and price impact, add minOut and maxIn

---

contracts/comments.js
test/comments.js

Provides a more stable token maintenance mechanism, using the rewardInterval for how often to increment rewards and do post payout computation.
Moreover, within the same reward interval, we will process all posts within this interval together, possibly spread over multiple maintenance periods
In order to schedule multiple tokens fairly, we change the token maintenance order by looping and iterating by ID instead of by processing timestamp.

Throttle by vote count in addition to max posts processed

---

contracts/marketpools.js
test/distribution.js

- The adjustment to `timeFactor` when liquidity is added was not working as intended. It was resetting to current block time in essentially all cases. The changes in this PR correct this.
- Tests for these operations are in the `distribution` contract test suite.
Intended functionality:
Example: a position is increased by 100% (doubled) on period 4 after initial deposit; timeFactor will be increased by 2 periods / bonus level will be reduced by 2 periods. After adding liquidity the effective bonus shares remains consistent.
The 24 hour holding time remains in effect to prevent abuse, and with this correction to timeFactor, should only affect a small number of situations where liquidity is added and then increased by a great order of magnitude shortly after.

Distribution: bonus curve adjustment fix

---

contracts/comments.js
libs/Block.js
test/comments.js

Rollforward of #111  with fix.
Fixes interval adding all posts within range, and allows comments to paid out posts to be properly indexed, and does not allow comments to re-activate after payout.
Adds new table called 'postMetadata' that maps authorperm to rewardPoolIds. Can be extended to store more in the future if needed. Lookups are by primary key _id, should be efficient, and does not affect the index for posts for a given reward pool.
This also adds a node change to make it so that MongoErrors properly error out completely rather than allow the node to infinite loop.

Rollforward: Keep track of previously processed posts

---

contracts/comments.js
test/comments.js

Allows token issuer to reset reward pool, which will set claims to 0, reward pool to 0, and reset start time so that new votes will accumulate claims as well.

Comments reset pool

---

contracts/witnesses.js

This can cause divergence in log if payouts happen in a different order than others.

Witness schedule fix order

---

contracts/mining.js
contracts/nft.js
test/mining.js

Restore update functionality, and skip inactive pools .
Note that if a pool is inactive, to reactivate the pool owner should change a setting to recompute mining power right before so any nft changes since deactivation can be computed again. This can be a mining setting or a burn change action.
To deploy: first deploy mining, followed by nft.

Nft miner fix handle nft change

---

contracts/mining.js
test/mining.js

When an equipped nft is not in the type map, when we recompute balances, it fails to reset the nftBalances field.
Eventually, we should not need to do this anymore as we started to track equipped nft's and types directly in the miningpower object. This will make the update a lot faster as well. Needs subsequent fix.

fix issue where non-typemap equipped nfts do not reset balance on update

---

contracts/nftmarket.js
test/nftmarket.js

This is to prevent an error that can happen if a buyer tries to set itself as the market account to receive fees from NFT purchases.  Here's an example of one such invalid transaction:
https://he.dtools.dev/tx/63002c925da6f3a585f531bec353d45359c84f69
The solution is to disallow cases where the buyer account is the same as the marketAccount parameter or the officialMarket setting of the market.

Add extra validation for marketAccount and officialMarket settings

---

contracts/hivepegged.js
libs/util/contractUtil.js
package.json
test/hivepegged.js

Part of the fee structure changes going live at 8pm Eastern 1/25/22, described here: https://hive.blog/hive/@aggroed/fee-structure-changes-coming-to-hive-engine

Reduce fees for HIVE deposits & withdrawals from 1% to 0.75%

---

contracts/nftairdrops.js
package.json
test/nftairdrops.js

This Smart Contract allows NFT's to be airdropped, much like the Airdrops Contract for tokens. This way, a substantial amount of NFT's can be transferred to many different accounts, without having to manually create each transaction.
The NFT Airdrop Contract accepts a similar payload to that of the token Airdrops Contract. You specify the NFT symbol and a list of destination accounts. For each account, a list of NFT ID's needs to be provided that will be transferred to that account during the airdrop process.
```json
"symbol": "TUNZ",
"list":[
{"to": "bait002", "ids":["11", "12"]},
{"to": "aggroed", "ids": ["13", "6", "4"]},
{"to": "bennierex", "ids":["39"]},
{"to": "cryptomancer", "ids":["16"]},
{"to": "nftmarket", "toType": "contract", "ids": ["8", "9", "10"]}
],
"startBlockNumber": …
```

NFT Airdrop Contract

---

plugins/JsonRPCServer.js

This change adds the `lastVerifiedBlockNumber` to the `getStatus` request, by fetching it from the `witnesses` `params` table and adding it if present. I think this is rather useful to immediately check the state of hive-engine nodes, without having to perform a second request.

Add lastVerifiedBlockNumber to getStatus request

---

find_divergent_block.js

Retry on failure, up to 3 times, and with 500ms back-off, to help with throttling issues on primary node.

Find divergent block retries

---

plugins/Streamer.js

In HF26 the form beneficiaries are handled has changed (breaking change), which results in hive-engine nodes diverging, due to the beneficiaires not being parsed correctly.
Before the beneficiary format was the following:
```
"extensions": [
[
0,
{
"beneficiaries": [
{
"account": "alinares",
"weight": 300
},
{
"account": "hiveonboard",
"weight": 100
},
{
"account": "tipu",
"weight": 100
}]
}]
]
}]
],
```
and after HF26:
```
"extensions": [
{
"type": "comment_payout_beneficiaries",
"value": {
"beneficiaries": [
{
"account": "alinares",
"weight": 300
},
{
"account": "hiveonboard",
"weight": 100
},
{
"account": "tipu",
"weight": 100
}]
}
}]
}]
],
```
The change adds an additional if case parsing the new beneficiary format.

Fix HF26 breaking change for beneficiaries in Streamer.js

---

witness_action.js

Appending -v to `witness_actions.js` will let user choose to verify their transaction, and with -e they can specify an engine node to verify against.

Add ability to verify transactions from witness_actions.js

---

contracts/inflation.js
contracts/witnesses.js
test/witnesses.js

This PR doubles BEE inflation for witness pay from 100k BEE per year to 200k BEE per year, and also changes payouts to give staked tokens rather than liquid tokens.

Increase witness pay

---

find_divergent_block.js
witness_action.js

The scrip to find divergence will run before registering a witness. Can be skipped by using option -s. Uses head only comparison for speed.

Run a divergence check before registering witnesses

---

config.json
plugins/JsonRPCServer.js

Adds 3 new config parameters, `rpcConfig.maxLimit`, `rpcConfig.maxOffset` and `rpcConfig.logRequests`. `maxLimit` is the greatest limit that will be allowed in find queries, the highest possible value is 1000. `maxOffset` is the maximum allowable offset, with -1 being for no max. `logRequests` lets the requests to the node be logged, with the format of INCOMING_IP - INCOMING_BODY.

Allows for RPC Config
