hive-engine/steemsmartcontracts

contracts/market.js
test/market.js

This change adds two new contract actions:
marketBuy
marketSell

Add support for market orders

---

contracts/market.js
test/hivesmartcontracts.js
test/market.js

Added the following market contract actions (ported from SE version):
1. marketBuy
2. marketSell

Support for market orders on HE

---

contracts/airdrops.js
libs/Block.js
package.json
test/airdrops.js

adding airdrops smart contract, airdrops test file, virtual transaction every block for it.

Airdrops Smart Contract

---

contracts/claimdrops.js
libs/Block.js
package.json
test/claimdrops.js

Claimdrops Smart Contract, can be used to create coin offering with custom prices. creates a pool which has a expiration time upto 90 days (variable) and maximum claims (variable). anyone or selected users can claim tokens for the defined price in Hive Pegged token (similar to market). there can be a claim limit for everyone or individuals in a list which can go up than the pool itself so its first to fill the pool. the price collected, and pool (if remaining) after the expiration is sent to a account or contract defined by owner.
Actions:
* create: creates a claimdrop
fee 50 BEE and 0.1*maxClaims is burned.
* claim: can claim tokens from an active claimdrop
price in SWAP.HIVE is sent to the owner, it is calculated by quantity parameter. price*quantity (price defined in the claimdrop)

Claimdrops Smart Contract

---

libs/Database.js

Also makes sure no operations flush caches (e.g. reads) if there is no session, which could be problematic.

disable cache on reads if no session (e.g. RPC / P2P)

---

plugins/P2P.js

await on verify round handler to properly handle errors, and add null check for last proposed round

Fix P2P stall issue in certain cases

---

contracts/marketpools.js
test/marketpools.js

This contract provides an additional decentralized exchange (DEX) for hive engine tokens using automated market making with a liquidity protocol. The pricing model uses the constant product formula (```x * y = k```) with no fees taken from traders. Pools are created and funded in a manner similar to other well-known implementations and swaps are intended to be executed in as simple a manner as possible (i.e. buy X tokens for Y, buy Y tokens for X).
An internal oracle to the hive engine order book provides a sanity check when initializing new pool liquidity, and ensures the pool starts with a realistic market price.
Every swap is checked for maximum slippage to prevent a large order relative to available liquidity pool from dramatically affecting the price.
Each pool collects some …

Automated market making pools for token exchange

---

contracts/marketpools.js
test/marketpools.js

- restricts `sharesOut` and `maxSlippage` precision to <= 3
- fix error messages to show actual amount being compared in `validateSwap`
- change to string asserts on user input
- **change `addLiquidity` validation to calculate optimal values within new tolerance parameter**
Should not modify schema or any existing data in the DB.

diesel pools launch revisions

---

witness_action.js

No response was given previously. This fixes that and has the action give a response.

Fix logging of witness_actions

---

contracts/witnesses.js
plugins/P2P.js
test/witnesses.js

updateParams will auto reset schedule if the witness number differs.
Also, cleans up old gates that are no longer used.

add witness updateParams action

---

contracts/comments.js

Testing this on the testnet, should speed up queries during post payout processing.

fix comment vote queries

---

contracts/marketpools.js
test/marketpools.js

Essentially changing api.BigNumber.ROUND_HALF_UP to api.BigNumber.ROUND_DOWN on the output from the contract. Also minor code cleanup for readability and test case.

Rounding outputs for tokens of smaller precision

---

contracts/distribution.js
contracts/marketpools.js
contracts/testing/dummyTicks.js
libs/Block.js
libs/Constants.js
libs/Database.js
libs/SmartContracts.js
package.json
test/distribution.js
test/ticks.js

Complete rewrite of the distribution contract to add a new distribution strategy using diesel pool liquidity providers and retain existing functionality for fixed distributions.
Both strategies now distribute by virtual transaction over a specified number of ticks (similar to unstaking), or the distribution owner can flush the pending amounts manually. Initial tick time is set to 24 hours for a daily distribution.
~~WIP: payout tx limit and spreading over future blocks~~
depends on #81

Updated Distribution Contract

---

contracts/marketpools.js
test/marketpools.js

When adding liquidity to a new pool, this allows user to set their own deviation from the HE market or disable this check entirely.

addLiquidity payload to control maximum deviation from HE market

---

contracts/distribution.js
test/distribution.js

@bt-cryptomancer 
Used a return in validation when it should have been a continue / if block.
- Refactored all returns in the runDistribution method.
- Test case to confirm functionality.
*Need to sync contract and distro balances before deploying update.

hotfix: distribution contract

---

contracts/inflation.js
contracts/tokenfunds.js
libs/util/contractUtil.js
test/tokenfunds.js

A method to create and supply BEE:WORKERBEE and BEE:BEE token funds.
* test coverage for the inflation contract parts are in the tokenfunds test suite
* activation block number TBD
* requires #86 for distribution to accept funds

Possible utility/governance token DTF creation from inflation contract

---

contracts/tokenfunds.js

Note: tests not passing until #93 is merged

DTF proposal update validation fix

---

contracts/comments.js
test/comments.js

This will fix issues with maintenance actions failing maintenance due to not being able to issue tokens

only do maintenance on null ops

---

libs/SmartContracts.js

Causing nodes to hang on a block with a lot of property setting

disable handleNftChange as very inefficient

---

libs/Block.js
libs/SmartContracts.js

Allows replay from previous snapshot to gate new behavior on block number.

Fix handle nft change with block number

---

config.json
find_divergent_block.js

remove ausbt as utf strangeness and find divergent looks at whole hash now and shows full block

Better defaults, find divergent script improvements

---

libs/Database.js
test/comments.js
test/market.js
test/nft.js
test/tokens.js
test/witnesses.js

Tested on local node, matches perfectly with current behavior, and confirmed fixed divegence source for other witnesses.

add default sort explicitly to prevent dependency on "natural" order

---

contracts/marketpools.js
test/marketpools.js

Addition of a **0.25% fee** for swapping tokens. The fee is immediately deposited to liquidity reserves and increases the proportional value of all liquidity provider shares. LPs realize the gain when removing liquidity.

Contract Update: marketpools fee

---

find_divergent_block.js

* Appending -h to find_divergent_block.js will only compare head blocks instead of doing a high / low check
* Light nodes use the default check and start with `low = firstBlockNumber` instead of `low = 0` (`firstBlockNumber` is the first block stored by a light node)

find divergent block - introduce -h flag to only compare head blocks
